#!/usr/bin/env bun
// Emits contracts/borrow-pool/src/poseidon_constants.rs from
// features/notes/poseidon-constants.json. Same source of truth as the
// JS Poseidon in features/notes/poseidon.ts — if the JSON changes,
// both consumers regenerate in one command.
//
// The JSON stores circomlib's optimized Poseidon constants:
//   C[t]  round constants (R_F*t + R_P total)
//   M[t]  MDS matrix (t × t)
//   P[t]  transition matrix (t × t)
//   S[t]  sparse partial-round constants (R_P * (2t - 1))
//
// Usage:
//   bun contracts/scripts/gen-poseidon-constants.ts

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"

const REPO_ROOT = resolve(__dirname, "..", "..")
const CONSTANTS_JSON = resolve(REPO_ROOT, "features/notes/poseidon-constants.json")
const OUTPUT_RS = resolve(
  REPO_ROOT,
  "contracts/borrow-pool/src/poseidon_constants.rs"
)

// Matches features/notes/poseidon.ts. Do not diverge.
const FR_ORDER =
  0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001n

const R_F = 8
const R_P: Record<number, number> = { 3: 57, 5: 60, 7: 63 }
const SUPPORTED_WIDTHS = [3, 5, 7] as const

type Raw = {
  C: Record<string, string[]>
  M: Record<string, string[][]>
  P: Record<string, string[][]>
  S: Record<string, string[]>
}

const raw = JSON.parse(readFileSync(CONSTANTS_JSON, "utf8")) as Raw

function toFieldElement(hex: string): bigint {
  const value = BigInt(hex) % FR_ORDER
  return value < 0n ? value + FR_ORDER : value
}

function toBytes32BE(value: bigint): number[] {
  const bytes = new Array<number>(32).fill(0)
  let residue = value
  for (let byteIndex = 31; byteIndex >= 0; byteIndex--) {
    bytes[byteIndex] = Number(residue & 0xffn)
    residue >>= 8n
  }
  return bytes
}

function formatBytesLiteral(bytes: number[]): string {
  return `[${bytes.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")}]`
}

const lines: string[] = []
lines.push(
  "//! Poseidon round constants for the circomlib-optimized variant,"
)
lines.push(
  "//! widths t = 3, 5, 7. Auto-generated by"
)
lines.push("//! `contracts/scripts/gen-poseidon-constants.ts` from")
lines.push("//! `features/notes/poseidon-constants.json`. Do not hand-edit.")
lines.push("")
lines.push(`pub const R_F: usize = ${R_F};`)
lines.push("")
for (const t of SUPPORTED_WIDTHS) {
  lines.push(`pub const R_P_T${t}: usize = ${R_P[t]};`)
}
lines.push("")

for (const t of SUPPORTED_WIDTHS) {
  const c = raw.C[String(t)]
  const expectedC = R_F * t + R_P[t]
  if (c.length !== expectedC) {
    throw new Error(
      `t=${t}: expected ${expectedC} C constants, got ${c.length}`
    )
  }
  lines.push(`pub const C_T${t}: [[u8; 32]; ${c.length}] = [`)
  for (const hex of c) {
    lines.push(`    ${formatBytesLiteral(toBytes32BE(toFieldElement(hex)))},`)
  }
  lines.push("];")
  lines.push("")

  emitMatrix("M", t, raw.M[String(t)])
  emitMatrix("P", t, raw.P[String(t)])

  const s = raw.S[String(t)]
  const expectedS = R_P[t] * (2 * t - 1)
  if (s.length !== expectedS) {
    throw new Error(
      `t=${t}: expected ${expectedS} S entries, got ${s.length}`
    )
  }
  lines.push(`pub const S_T${t}: [[u8; 32]; ${s.length}] = [`)
  for (const hex of s) {
    lines.push(`    ${formatBytesLiteral(toBytes32BE(toFieldElement(hex)))},`)
  }
  lines.push("];")
  lines.push("")
}

if (!existsSync(dirname(OUTPUT_RS)))
  mkdirSync(dirname(OUTPUT_RS), { recursive: true })
writeFileSync(OUTPUT_RS, lines.join("\n") + "\n")
console.log(`Wrote ${OUTPUT_RS} (${lines.length} lines).`)

function emitMatrix(name: "M" | "P", t: number, matrix: string[][]): void {
  if (matrix.length !== t) {
    throw new Error(`t=${t}: expected ${t} ${name} rows, got ${matrix.length}`)
  }
  lines.push(`pub const ${name}_T${t}: [[[u8; 32]; ${t}]; ${t}] = [`)
  for (const row of matrix) {
    if (row.length !== t) {
      throw new Error(
        `t=${t}: expected ${t} ${name} columns per row, got ${row.length}`
      )
    }
    lines.push("    [")
    for (const hex of row) {
      lines.push(
        `        ${formatBytesLiteral(toBytes32BE(toFieldElement(hex)))},`
      )
    }
    lines.push("    ],")
  }
  lines.push("];")
  lines.push("")
}
