#!/usr/bin/env bun
// Emits contracts/borrow-pool/tests/poseidon_fixtures.txt — a text
// table of `input… -> output` pairs produced by the JS Poseidon
// (features/notes/poseidon.ts). Once soroban-sdk `testutils` is
// unblocked, the Rust cross-check will parse this file and assert
// bit-identical output. Until then, the file lives as authoritative
// oracle output that a manual integration test can compare against.
//
// Usage:
//   bun contracts/scripts/gen-poseidon-fixtures.ts

import { writeFileSync } from "node:fs"
import { resolve } from "node:path"

import { poseidon } from "../../features/notes/poseidon"

const REPO_ROOT = resolve(__dirname, "..", "..")
const OUTPUT = resolve(
  REPO_ROOT,
  "contracts/borrow-pool/tests/poseidon_fixtures.txt"
)

type Fixture = { inputs: bigint[]; label: string }

const FIXTURES: Fixture[] = [
  { label: "t=3 all-zero", inputs: [0n, 0n] },
  { label: "t=3 small", inputs: [1n, 2n] },
  {
    label: "t=3 large",
    inputs: [
      0x1234567890abcdef1234567890abcdefn,
      0xdeadbeefcafebabe1234567890abcdefn,
    ],
  },
  { label: "t=5 all-zero", inputs: [0n, 0n, 0n, 0n] },
  { label: "t=5 sequential", inputs: [1n, 2n, 3n, 4n] },
  {
    label: "t=5 commitment-shape",
    inputs: [100n, 0n, 7n, 42n], // amount=100, asset=XLM(0), sk=7, salt=42
  },
  { label: "t=7 all-zero", inputs: [0n, 0n, 0n, 0n, 0n, 0n] },
  { label: "t=7 mixed", inputs: [1n, 2n, 3n, 4n, 5n, 6n] },
]

function toHex(value: bigint): string {
  return `0x${value.toString(16).padStart(64, "0")}`
}

const lines: string[] = []
lines.push("# Poseidon cross-check fixtures (BLS12-381 Fr).")
lines.push("# Generated by contracts/scripts/gen-poseidon-fixtures.ts")
lines.push("# Format: label ; inputs (hex, comma-separated) ; output (hex)")
lines.push("")

for (const fixture of FIXTURES) {
  const output = poseidon(fixture.inputs)
  const inputsHex = fixture.inputs.map(toHex).join(",")
  lines.push(`${fixture.label} ; ${inputsHex} ; ${toHex(output)}`)
}

writeFileSync(OUTPUT, lines.join("\n") + "\n")
console.log(`Wrote ${OUTPUT} (${FIXTURES.length} fixtures).`)
