#!/usr/bin/env bun
// Emits contracts/borrow-pool/src/poseidon_constants.rs from
// features/notes/poseidon-constants.json. Same source of truth as the
// JS Poseidon in features/notes/poseidon.ts — if the JSON changes,
// both consumers regenerate in one command.
//
// Usage:
//   bun contracts/scripts/gen-poseidon-constants.ts

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"

const REPO_ROOT = resolve(__dirname, "..", "..")
const CONSTANTS_JSON = resolve(REPO_ROOT, "features/notes/poseidon-constants.json")
const OUTPUT_RS = resolve(
  REPO_ROOT,
  "contracts/borrow-pool/src/poseidon_constants.rs"
)

// Matches features/notes/poseidon.ts. Do not diverge.
const FR_ORDER =
  0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001n

const R_F = 8
const R_P: Record<number, number> = { 3: 57, 5: 60, 7: 63 }
const SUPPORTED_WIDTHS = [3, 5, 7] as const

type Raw = {
  C: Record<string, string[]>
  M: Record<string, string[][]>
}

const raw = JSON.parse(readFileSync(CONSTANTS_JSON, "utf8")) as Raw

function toFieldElement(hex: string): bigint {
  const value = BigInt(hex) % FR_ORDER
  return value < 0n ? value + FR_ORDER : value
}

function toBytes32BE(value: bigint): number[] {
  const bytes = new Array<number>(32).fill(0)
  let residue = value
  for (let byteIndex = 31; byteIndex >= 0; byteIndex--) {
    bytes[byteIndex] = Number(residue & 0xffn)
    residue >>= 8n
  }
  return bytes
}

function formatBytesLiteral(bytes: number[]): string {
  return `[${bytes.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")}]`
}

const lines: string[] = []
lines.push(
  "//! Poseidon round constants + MDS matrix for widths t = 3, 5, 7."
)
lines.push(
  "//! Auto-generated by `contracts/scripts/gen-poseidon-constants.ts` from"
)
lines.push("//! `features/notes/poseidon-constants.json`. Do not hand-edit.")
lines.push("")
lines.push(`pub const R_F: usize = ${R_F};`)
lines.push("")
for (const t of SUPPORTED_WIDTHS) {
  lines.push(`pub const R_P_T${t}: usize = ${R_P[t]};`)
}
lines.push("")

for (const t of SUPPORTED_WIDTHS) {
  const constants = raw.C[String(t)]
  const totalRounds = R_F + R_P[t]
  const expected = totalRounds * t
  if (constants.length !== expected) {
    throw new Error(
      `t=${t}: expected ${expected} constants (${totalRounds} rounds × ${t}), got ${constants.length}`
    )
  }
  lines.push(`pub const C_T${t}: [[u8; 32]; ${constants.length}] = [`)
  for (const hex of constants) {
    const bytes = toBytes32BE(toFieldElement(hex))
    lines.push(`    ${formatBytesLiteral(bytes)},`)
  }
  lines.push("];")
  lines.push("")

  const matrix = raw.M[String(t)]
  if (matrix.length !== t) {
    throw new Error(`t=${t}: expected ${t} MDS rows, got ${matrix.length}`)
  }
  lines.push(`pub const M_T${t}: [[[u8; 32]; ${t}]; ${t}] = [`)
  for (const row of matrix) {
    if (row.length !== t) {
      throw new Error(
        `t=${t}: expected ${t} MDS columns per row, got ${row.length}`
      )
    }
    lines.push("    [")
    for (const hex of row) {
      const bytes = toBytes32BE(toFieldElement(hex))
      lines.push(`        ${formatBytesLiteral(bytes)},`)
    }
    lines.push("    ],")
  }
  lines.push("];")
  lines.push("")
}

if (!existsSync(dirname(OUTPUT_RS))) mkdirSync(dirname(OUTPUT_RS), { recursive: true })
writeFileSync(OUTPUT_RS, lines.join("\n") + "\n")
console.log(`Wrote ${OUTPUT_RS} (${lines.length} lines).`)
