#!/usr/bin/env bun
// Emits contracts/borrow-pool/tests/merkle_fixtures.txt — sequential
// append states so the Rust merkle module can be cross-checked once
// unit tests are wired up. Same "oracle output" pattern as the
// Poseidon fixture generator.

import { writeFileSync } from "node:fs"
import { resolve } from "node:path"

import { append, DEPTH, emptyRoot } from "../../features/notes/merkle"

const REPO_ROOT = resolve(__dirname, "..", "..")
const OUTPUT = resolve(
  REPO_ROOT,
  "contracts/borrow-pool/tests/merkle_fixtures.txt"
)

function toHex(value: bigint): string {
  return `0x${value.toString(16).padStart(64, "0")}`
}

const frontier = new Array<bigint>(DEPTH).fill(0n)
const lines: string[] = []
lines.push("# Incremental Merkle append fixtures (BLS12-381 Fr).")
lines.push("# Generated by contracts/scripts/gen-merkle-fixtures.ts")
lines.push(`# Depth: ${DEPTH}`)
lines.push(`# empty_root: ${toHex(emptyRoot())}`)
lines.push("# Format: index ; leaf (hex) ; new_root (hex)")
lines.push("")

for (let index = 0; index < 8; index++) {
  const leaf = BigInt(0x1000 + index)
  const { root } = append({ frontier, leaf, nextIndex: index })
  lines.push(`${index} ; ${toHex(leaf)} ; ${toHex(root)}`)
}

writeFileSync(OUTPUT, lines.join("\n") + "\n")
console.log(`Wrote ${OUTPUT} (8 fixtures).`)
