// Auto-generated by `stellar contract bindings typescript`.
// Do not hand-edit — regenerate via
// `stellar contract bindings typescript --network testnet --contract-id <id> --output-dir <dir>`
// and copy `src/index.ts` back here.
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/ban-ts-comment, @typescript-eslint/no-unsafe-declaration-merging */

import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CDOQVJ75M4EZAS7MX6ADUIHJCEMSUUSL2ABAS3LO2LZTQ7FFLRGS2DTI",
  }
} as const

export const Errors = {
  1: {message:"IntentExpired"},
  2: {message:"ProofReplayed"},
  3: {message:"InvalidAmount"},
  4: {message:"StaleOracle"},
  5: {message:"InvalidProof"}
}


export interface BorrowProof {
  /**
 * Oracle epoch the proof was generated against.
 */
oracle_epoch: u64;
  /**
 * Poseidon2 commitment to (oracle_price, salt) the prover used.
 */
oracle_price_commitment: Buffer;
  /**
 * Serialized Groth16 proof: A (G1) || B (G2) || C (G1).
 */
proof_bytes: Buffer;
}


export interface BorrowIntent {
  account: string;
  borrow_amount: i128;
  borrow_symbol: string;
  collateral_amount: i128;
  collateral_symbol: string;
  expires_at: u64;
  health_factor_bps: u32;
  market: string;
  max_ltv_bps: u32;
  proof_id: Buffer;
}


export interface BorrowReceipt {
  account: string;
  borrow_amount: i128;
  borrow_symbol: string;
  collateral_amount: i128;
  collateral_symbol: string;
  confirmed_at: u64;
  proof_id: Buffer;
}

export interface Client {
  /**
   * Construct and simulate a borrow transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  borrow: ({intent, proof}: {intent: BorrowIntent, proof: BorrowProof}, options?: MethodOptions) => Promise<AssembledTransaction<Result<BorrowReceipt>>>

  /**
   * Construct and simulate a position transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  position: ({account}: {account: string}, options?: MethodOptions) => Promise<AssembledTransaction<Option<BorrowReceipt>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAAAAAAAAGYm9ycm93AAAAAAACAAAAAAAAAAZpbnRlbnQAAAAAB9AAAAAMQm9ycm93SW50ZW50AAAAAAAAAAVwcm9vZgAAAAAAB9AAAAALQm9ycm93UHJvb2YAAAAAAQAAA+kAAAfQAAAADUJvcnJvd1JlY2VpcHQAAAAAAAAD",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABQAAAAAAAAANSW50ZW50RXhwaXJlZAAAAAAAAAEAAAAAAAAADVByb29mUmVwbGF5ZWQAAAAAAAACAAAAAAAAAA1JbnZhbGlkQW1vdW50AAAAAAAAAwAAAAAAAAALU3RhbGVPcmFjbGUAAAAABAAAAAAAAAAMSW52YWxpZFByb29mAAAABQ==",
        "AAAAAAAAAAAAAAAIcG9zaXRpb24AAAABAAAAAAAAAAdhY2NvdW50AAAAABMAAAABAAAD6AAAB9AAAAANQm9ycm93UmVjZWlwdAAAAA==",
        "AAAAAQAAAAAAAAAAAAAAC0JvcnJvd1Byb29mAAAAAAMAAAAtT3JhY2xlIGVwb2NoIHRoZSBwcm9vZiB3YXMgZ2VuZXJhdGVkIGFnYWluc3QuAAAAAAAADG9yYWNsZV9lcG9jaAAAAAYAAAA9UG9zZWlkb24yIGNvbW1pdG1lbnQgdG8gKG9yYWNsZV9wcmljZSwgc2FsdCkgdGhlIHByb3ZlciB1c2VkLgAAAAAAABdvcmFjbGVfcHJpY2VfY29tbWl0bWVudAAAAAPuAAAAIAAAADVTZXJpYWxpemVkIEdyb3RoMTYgcHJvb2Y6IEEgKEcxKSB8fCBCIChHMikgfHwgQyAoRzEpLgAAAAAAAAtwcm9vZl9ieXRlcwAAAAAO",
        "AAAAAQAAAAAAAAAAAAAADEJvcnJvd0ludGVudAAAAAoAAAAAAAAAB2FjY291bnQAAAAAEwAAAAAAAAANYm9ycm93X2Ftb3VudAAAAAAAAAsAAAAAAAAADWJvcnJvd19zeW1ib2wAAAAAAAARAAAAAAAAABFjb2xsYXRlcmFsX2Ftb3VudAAAAAAAAAsAAAAAAAAAEWNvbGxhdGVyYWxfc3ltYm9sAAAAAAAAEQAAAAAAAAAKZXhwaXJlc19hdAAAAAAABgAAAAAAAAARaGVhbHRoX2ZhY3Rvcl9icHMAAAAAAAAEAAAAAAAAAAZtYXJrZXQAAAAAABEAAAAAAAAAC21heF9sdHZfYnBzAAAAAAQAAAAAAAAACHByb29mX2lkAAAD7gAAACA=",
        "AAAAAQAAAAAAAAAAAAAADUJvcnJvd1JlY2VpcHQAAAAAAAAHAAAAAAAAAAdhY2NvdW50AAAAABMAAAAAAAAADWJvcnJvd19hbW91bnQAAAAAAAALAAAAAAAAAA1ib3Jyb3dfc3ltYm9sAAAAAAAAEQAAAAAAAAARY29sbGF0ZXJhbF9hbW91bnQAAAAAAAALAAAAAAAAABFjb2xsYXRlcmFsX3N5bWJvbAAAAAAAABEAAAAAAAAADGNvbmZpcm1lZF9hdAAAAAYAAAAAAAAACHByb29mX2lkAAAD7gAAACA=" ]),
      options
    )
  }
  public readonly fromJSON = {
    borrow: this.txFromJSON<Result<BorrowReceipt>>,
        position: this.txFromJSON<Option<BorrowReceipt>>
  }
}