//! Poseidon over BLS12-381 `Fr` — mirror of `features/notes/poseidon.ts`
//! which itself mirrors `circomlib/circuits/poseidon.circom` under
//! `-p bls12381`. Any drift here breaks every shielded proof.
//!
//! Constants come from `poseidon_constants.rs`, itself generated by
//! `contracts/scripts/gen-poseidon-constants.ts` from the shared
//! `features/notes/poseidon-constants.json` — regenerate both sides
//! when the JSON changes.
//!
//! Supported input widths: 2 / 4 / 6 (state widths t = 3 / 5 / 7).
//! Every hash arity our circuits + contract need lands in that set.
//!
//! The permutation follows circomlib's optimised variant: full rounds
//! at both ends of the schedule use the MDS matrix `M`; the transition
//! round (last of the first half) mixes with `P`; partial rounds use
//! `S`-based sparse mixing. This matches the exact set of constraints
//! the circom circuits emit, so the leaves the client + contract
//! compute agree with the leaves the circuits verify.

#![allow(dead_code)]

use soroban_sdk::{crypto::bls12_381::Fr, BytesN, Env};

use crate::poseidon_constants::{
    C_T3, C_T5, C_T7, M_T3, M_T5, M_T7, P_T3, P_T5, P_T7, R_F, R_P_T3, R_P_T5,
    R_P_T7, S_T3, S_T5, S_T7,
};

const T3: usize = 3;
const T5: usize = 5;
const T7: usize = 7;

fn fr_from_bytes(env: &Env, bytes: &[u8; 32]) -> Fr {
    let buf = BytesN::from_array(env, bytes);
    Fr::from_bytes(buf)
}

fn add(env: &Env, lhs: &Fr, rhs: &Fr) -> Fr {
    env.crypto().bls12_381().fr_add(lhs, rhs)
}

fn mul(env: &Env, lhs: &Fr, rhs: &Fr) -> Fr {
    env.crypto().bls12_381().fr_mul(lhs, rhs)
}

fn pow5(env: &Env, value: &Fr) -> Fr {
    let squared = mul(env, value, value);
    let fourth = mul(env, &squared, &squared);
    mul(env, &fourth, value)
}

/// Poseidon(inputs). Length 2 → t=3; length 4 → t=5; length 6 → t=7.
/// Any other width panics — the circuits and the client never call
/// with other widths, so failing loudly here catches wiring bugs.
pub fn poseidon(env: &Env, inputs: &[Fr]) -> Fr {
    match inputs.len() {
        2 => permute::<T3>(
            env,
            inputs,
            R_P_T3,
            &c_t3(env),
            &m_t3(env),
            &p_t3(env),
            &s_t3(env),
        ),
        4 => permute::<T5>(
            env,
            inputs,
            R_P_T5,
            &c_t5(env),
            &m_t5(env),
            &p_t5(env),
            &s_t5(env),
        ),
        6 => permute::<T7>(
            env,
            inputs,
            R_P_T7,
            &c_t7(env),
            &m_t7(env),
            &p_t7(env),
            &s_t7(env),
        ),
        other => panic!("poseidon: unsupported input width {}", other),
    }
}

pub fn hash2(env: &Env, a: &Fr, b: &Fr) -> Fr {
    poseidon(env, &[a.clone(), b.clone()])
}

pub fn hash4(env: &Env, a: &Fr, b: &Fr, c: &Fr, d: &Fr) -> Fr {
    poseidon(env, &[a.clone(), b.clone(), c.clone(), d.clone()])
}

pub fn hash6(env: &Env, a: &Fr, b: &Fr, c: &Fr, d: &Fr, e: &Fr, f: &Fr) -> Fr {
    poseidon(
        env,
        &[
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
        ],
    )
}

pub fn hash_two_to_one(env: &Env, left: &Fr, right: &Fr) -> Fr {
    hash2(env, left, right)
}

fn permute<const T: usize>(
    env: &Env,
    inputs: &[Fr],
    partial_rounds: usize,
    constants: &[Fr],
    matrix_m: &[[Fr; T]; T],
    matrix_p: &[[Fr; T]; T],
    sparse_s: &[Fr],
) -> Fr {
    debug_assert_eq!(inputs.len() + 1, T);

    let zero = Fr::from_bytes(BytesN::from_array(env, &[0u8; 32]));

    // Initial state: state[0] = 0, state[1..] = inputs.
    let mut state: [Fr; T] = core::array::from_fn(|_| zero.clone());
    for (i, input) in inputs.iter().enumerate() {
        state[i + 1] = input.clone();
    }

    // ark[0]: add first `T` constants.
    for i in 0..T {
        state[i] = add(env, &state[i], &constants[i]);
    }

    // First half full rounds — R_F/2 - 1 iterations. Each round:
    // sigma → ark(next) → mix with M.
    let half = R_F / 2;
    for r in 0..(half - 1) {
        for i in 0..T {
            state[i] = pow5(env, &state[i]);
        }
        let base = (r + 1) * T;
        for i in 0..T {
            state[i] = add(env, &state[i], &constants[base + i]);
        }
        state = mix_matrix::<T>(env, matrix_m, &state, &zero);
    }

    // Transition round: sigma → ark → mix with P.
    for i in 0..T {
        state[i] = pow5(env, &state[i]);
    }
    let base = half * T;
    for i in 0..T {
        state[i] = add(env, &state[i], &constants[base + i]);
    }
    state = mix_matrix::<T>(env, matrix_p, &state, &zero);

    // Partial rounds using sparse S.
    let stride = 2 * T - 1;
    for r in 0..partial_rounds {
        state[0] = pow5(env, &state[0]);
        state[0] = add(env, &state[0], &constants[(half + 1) * T + r]);
        let s0 = state[0].clone();
        let mut acc = zero.clone();
        for j in 0..T {
            let term = mul(env, &sparse_s[r * stride + j], &state[j]);
            acc = add(env, &acc, &term);
        }
        let mut new_state: [Fr; T] = core::array::from_fn(|_| zero.clone());
        new_state[0] = acc;
        for i in 1..T {
            let term = mul(env, &s0, &sparse_s[r * stride + T + i - 1]);
            new_state[i] = add(env, &state[i], &term);
        }
        state = new_state;
    }

    // Second half full rounds — R_F/2 - 1 iterations. Each: sigma →
    // ark → mix with M.
    for r in 0..(half - 1) {
        for i in 0..T {
            state[i] = pow5(env, &state[i]);
        }
        let base = (half + 1) * T + partial_rounds + r * T;
        for i in 0..T {
            state[i] = add(env, &state[i], &constants[base + i]);
        }
        state = mix_matrix::<T>(env, matrix_m, &state, &zero);
    }

    // Final full sigma + MixLast column 0: out = Σ_j M[j][0] * state[j].
    for i in 0..T {
        state[i] = pow5(env, &state[i]);
    }
    let mut out = zero.clone();
    for j in 0..T {
        let term = mul(env, &matrix_m[j][0], &state[j]);
        out = add(env, &out, &term);
    }
    out
}

fn mix_matrix<const T: usize>(
    env: &Env,
    matrix: &[[Fr; T]; T],
    state: &[Fr; T],
    zero: &Fr,
) -> [Fr; T] {
    // out[i] = Σ_j matrix[j][i] * state[j] — matches circomlib's Mix
    // template (`lc += M[j][i] * in[j]`).
    let mut next: [Fr; T] = core::array::from_fn(|_| zero.clone());
    for i in 0..T {
        let mut acc = zero.clone();
        for j in 0..T {
            let term = mul(env, &matrix[j][i], &state[j]);
            acc = add(env, &acc, &term);
        }
        next[i] = acc;
    }
    next
}

fn c_t3(env: &Env) -> [Fr; C_T3.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T3[i]))
}

fn m_t3(env: &Env) -> [[Fr; T3]; T3] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T3[i][j])))
}

fn p_t3(env: &Env) -> [[Fr; T3]; T3] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &P_T3[i][j])))
}

fn s_t3(env: &Env) -> [Fr; S_T3.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &S_T3[i]))
}

fn c_t5(env: &Env) -> [Fr; C_T5.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T5[i]))
}

fn m_t5(env: &Env) -> [[Fr; T5]; T5] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T5[i][j])))
}

fn p_t5(env: &Env) -> [[Fr; T5]; T5] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &P_T5[i][j])))
}

fn s_t5(env: &Env) -> [Fr; S_T5.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &S_T5[i]))
}

fn c_t7(env: &Env) -> [Fr; C_T7.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T7[i]))
}

fn m_t7(env: &Env) -> [[Fr; T7]; T7] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T7[i][j])))
}

fn p_t7(env: &Env) -> [[Fr; T7]; T7] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &P_T7[i][j])))
}

fn s_t7(env: &Env) -> [Fr; S_T7.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &S_T7[i]))
}
