//! Poseidon hash for on-chain commitment / nullifier / Merkle tree
//! recomputation.
//!
//! This module MUST produce identical output to the Circom `Poseidon(t)`
//! templates from `circomlib` — the circuit and the contract both hash
//! the same commitment payload and the contract cross-checks the value
//! against the proof's public output. Any parameter drift between the
//! two sides makes every proof invalid.
//!
//! # Parameters
//!
//! Poseidon over the BLS12-381 scalar field `Fr`. State width `t`
//! variants: `t = 2, 3, 5, 7`. Round counts per `circomlib`:
//!   full rounds:     R_F = 8
//!   partial rounds:  R_P varies by `t` — 56 (t=2), 57 (t=3), 60 (t=5),
//!                    63 (t=7)
//! S-box: x^5 (α = 5 fits the field's multiplicative group).
//!
//! Round constants + MDS matrix come from `circomlib` — see
//! `contracts/scripts/gen-poseidon-constants.ts`, which reads circomlib
//! `constants.json` and emits `poseidon_constants.rs` so both sides
//! share one source of truth. The generator is a Phase-2 P task.
//!
//! # API surface
//!
//! Downstream (Merkle tree, nullifier derivation, commitment
//! recompute) only calls a small subset of arities:
//!
//! - `hash_two_to_one(l, r)`  — 2-input, Merkle interior nodes
//! - `hash2(a, b)`            — 2-input, nullifier `Poseidon(sk, index)`
//! - `hash4(a, b, c, d)`      — 4-input, commitment
//!                              `Poseidon(amount, asset_tag, sk, salt)`
//! - `hash6(a..f)`            — 6-input, oracle price commitment
//!                              (matches existing borrow-eligibility
//!                              `Poseidon(6)`)
//!
//! # Cross-check test
//!
//! `tests/poseidon_cross.rs` (added under Track P step 3) pins fixture
//! inputs against JS-side outputs produced by a small circomlib
//! wrapper script. Any deviation from the JS output = broken.
//!
//! # Status
//!
//! This is a scaffold — the permutation and constant tables land in
//! the next commit under Track P. Do not use in production until:
//!   1. `poseidon_constants.rs` is generated from circomlib source
//!   2. Permutation matches JS output over 10 random fixtures
//!   3. External review of the port

#![allow(dead_code)]

use soroban_sdk::crypto::bls12_381::Fr;

/// Placeholder that will hold the round constants + MDS matrix per
/// state width. Generated by `contracts/scripts/gen-poseidon-constants.ts`
/// against circomlib's `constants.json`. Not yet populated.
pub struct Params {
    pub t: usize,
    pub r_f: usize,
    pub r_p: usize,
}

pub const T2: Params = Params { t: 2, r_f: 8, r_p: 56 };
pub const T3: Params = Params { t: 3, r_f: 8, r_p: 57 };
pub const T5: Params = Params { t: 5, r_f: 8, r_p: 60 };
pub const T7: Params = Params { t: 7, r_f: 8, r_p: 63 };

/// Hash two field elements to one — the primitive Merkle interior
/// nodes call. Reduces to `hash2` internally.
///
/// TODO(P-2): implement permutation. Currently panics to guarantee
/// callers can't accidentally ship broken commitments.
pub fn hash_two_to_one(_env: &soroban_sdk::Env, _left: Fr, _right: Fr) -> Fr {
    panic!("poseidon::hash_two_to_one: not yet implemented (Track P step 2)")
}

/// Nullifier hash: `Poseidon(sk, index)`. Matches the circuit's
/// nullifier derivation so the on-chain replay guard can be recomputed
/// only inside the circuit (and never here — contract only stores /
/// checks membership).
pub fn hash2(_env: &soroban_sdk::Env, _a: Fr, _b: Fr) -> Fr {
    panic!("poseidon::hash2: not yet implemented (Track P step 2)")
}

/// Commitment hash: `Poseidon(amount, asset_tag, sk, salt)`. Every
/// deposit / borrow / repay uses this shape.
pub fn hash4(
    _env: &soroban_sdk::Env,
    _a: Fr,
    _b: Fr,
    _c: Fr,
    _d: Fr,
) -> Fr {
    panic!("poseidon::hash4: not yet implemented (Track P step 2)")
}

/// Oracle-price commitment: matches `Poseidon(6)` in the current
/// borrow-eligibility circuit's `commit` component so the contract's
/// Reflector cross-check aligns with what the prover embedded.
pub fn hash6(
    _env: &soroban_sdk::Env,
    _a: Fr,
    _b: Fr,
    _c: Fr,
    _d: Fr,
    _e: Fr,
    _f: Fr,
) -> Fr {
    panic!("poseidon::hash6: not yet implemented (Track P step 2)")
}
