//! Poseidon over BLS12-381 `Fr` — mirror of `features/notes/poseidon.ts`.
//!
//! Same round schedule, same S-box (x^5), same round constants + MDS
//! matrix. If this file's output ever diverges from the JS side, every
//! shielded proof breaks.
//!
//! Constants come from `poseidon_constants.rs`, itself generated by
//! `contracts/scripts/gen-poseidon-constants.ts` from the shared
//! `features/notes/poseidon-constants.json` — regenerate both sides
//! when the JSON changes.
//!
//! Supported input widths: 2 / 4 / 6 (state widths t = 3 / 5 / 7).
//! Every hash arity our circuits + contract need lands in that set.

#![allow(dead_code)]

use soroban_sdk::{crypto::bls12_381::Fr, BytesN, Env};

use crate::poseidon_constants::{
    C_T3, C_T5, C_T7, M_T3, M_T5, M_T7, R_F, R_P_T3, R_P_T5, R_P_T7,
};

const T3: usize = 3;
const T5: usize = 5;
const T7: usize = 7;

fn fr_from_bytes(env: &Env, bytes: &[u8; 32]) -> Fr {
    let buf = BytesN::from_array(env, bytes);
    Fr::from_bytes(buf)
}

fn add(env: &Env, lhs: &Fr, rhs: &Fr) -> Fr {
    env.crypto().bls12_381().fr_add(lhs, rhs)
}

fn mul(env: &Env, lhs: &Fr, rhs: &Fr) -> Fr {
    env.crypto().bls12_381().fr_mul(lhs, rhs)
}

fn pow5(env: &Env, value: &Fr) -> Fr {
    let squared = mul(env, value, value);
    let fourth = mul(env, &squared, &squared);
    mul(env, &fourth, value)
}

/// Poseidon(inputs). Length 2 → t=3; length 4 → t=5; length 6 → t=7.
/// Any other width panics — the circuits and the client never call
/// with other widths, so failing loudly here catches wiring bugs.
pub fn poseidon(env: &Env, inputs: &[Fr]) -> Fr {
    match inputs.len() {
        2 => permute::<T3>(env, inputs, R_P_T3, &c_t3(env), &m_t3(env)),
        4 => permute::<T5>(env, inputs, R_P_T5, &c_t5(env), &m_t5(env)),
        6 => permute::<T7>(env, inputs, R_P_T7, &c_t7(env), &m_t7(env)),
        other => panic!("poseidon: unsupported input width {}", other),
    }
}

// Convenience wrappers matching the JS-side API.
pub fn hash2(env: &Env, a: &Fr, b: &Fr) -> Fr {
    poseidon(env, &[a.clone(), b.clone()])
}

pub fn hash4(env: &Env, a: &Fr, b: &Fr, c: &Fr, d: &Fr) -> Fr {
    poseidon(env, &[a.clone(), b.clone(), c.clone(), d.clone()])
}

pub fn hash6(env: &Env, a: &Fr, b: &Fr, c: &Fr, d: &Fr, e: &Fr, f: &Fr) -> Fr {
    poseidon(
        env,
        &[
            a.clone(),
            b.clone(),
            c.clone(),
            d.clone(),
            e.clone(),
            f.clone(),
        ],
    )
}

/// Convenience for Merkle interior nodes.
pub fn hash_two_to_one(env: &Env, left: &Fr, right: &Fr) -> Fr {
    hash2(env, left, right)
}

fn permute<const T: usize>(
    env: &Env,
    inputs: &[Fr],
    partial_rounds: usize,
    constants: &[Fr],
    matrix: &[[Fr; T]; T],
) -> Fr {
    // Sanity: caller guarantees `T = inputs.len() + 1`.
    debug_assert_eq!(inputs.len() + 1, T);

    // Initialise state: state[0] = 0 (capacity), state[1..] = inputs.
    let mut state: [Fr; T] = core::array::from_fn(|_| Fr::from_bytes(BytesN::from_array(env, &[0u8; 32])));
    for (i, input) in inputs.iter().enumerate() {
        state[i + 1] = input.clone();
    }

    let total_rounds = R_F + partial_rounds;
    for round in 0..total_rounds {
        // Add round constants.
        for i in 0..T {
            let c = &constants[round * T + i];
            state[i] = add(env, &state[i], c);
        }

        // S-box. Full rounds cover every slot; partial rounds hit only
        // state[0] (Poseidon parameterisation).
        let is_full = round < R_F / 2 || round >= R_F / 2 + partial_rounds;
        if is_full {
            for i in 0..T {
                state[i] = pow5(env, &state[i]);
            }
        } else {
            state[0] = pow5(env, &state[0]);
        }

        // MDS matmul: next[i] = Σ_j M[i][j] * state[j].
        let mut next: [Fr; T] =
            core::array::from_fn(|_| Fr::from_bytes(BytesN::from_array(env, &[0u8; 32])));
        for i in 0..T {
            let mut acc = Fr::from_bytes(BytesN::from_array(env, &[0u8; 32]));
            for j in 0..T {
                let term = mul(env, &matrix[i][j], &state[j]);
                acc = add(env, &acc, &term);
            }
            next[i] = acc;
        }
        state = next;
    }

    state[0].clone()
}

// Load byte-array constants into `Fr` values lazily per call. The
// `Env` reference makes it hard to memoise across invocations in
// no_std Soroban, so we pay the marshalling cost every hash — Poseidon
// dominates anyway. Contract calls hash4/hash6 a handful of times per
// tx, not per round.

fn c_t3(env: &Env) -> [Fr; C_T3.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T3[i]))
}

fn m_t3(env: &Env) -> [[Fr; T3]; T3] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T3[i][j])))
}

fn c_t5(env: &Env) -> [Fr; C_T5.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T5[i]))
}

fn m_t5(env: &Env) -> [[Fr; T5]; T5] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T5[i][j])))
}

fn c_t7(env: &Env) -> [Fr; C_T7.len()] {
    core::array::from_fn(|i| fr_from_bytes(env, &C_T7[i]))
}

fn m_t7(env: &Env) -> [[Fr; T7]; T7] {
    core::array::from_fn(|i| core::array::from_fn(|j| fr_from_bytes(env, &M_T7[i][j])))
}

