//! Groth16 verifier over BLS12-381 for the borrow-eligibility circuit.
//!
//! Circuit + verifying key generated by:
//!
//!     cd contracts/circuits/borrow-eligibility-circom
//!     circom src/borrow_eligibility.circom -p bls12381 --r1cs --wasm -o build
//!     snarkjs powersoftau new bls12381 12 build/pot12_0000.ptau
//!     snarkjs powersoftau prepare phase2 build/pot12_0000.ptau build/pot12_final.ptau
//!     snarkjs groth16 setup build/borrow_eligibility.r1cs build/pot12_final.ptau build/borrow_eligibility.zkey
//!     snarkjs zkey export verificationkey build/borrow_eligibility.zkey build/verification_key.json
//!
//! The VK constants are then extracted to raw uncompressed BLS12-381 bytes
//! via `bun contracts/scripts/vk-json-to-bytes.ts` and embedded via
//! `include_bytes!`.
//!
//! Verifier follows the pattern in `stellar/soroban-examples/groth16_verifier`
//! and uses the native BLS12-381 host functions shipped in Protocol 22
//! (CAP-0059).

use soroban_sdk::{
    crypto::bls12_381::{Fr, G1Affine, G2Affine},
    vec, Env, Vec,
};

// Uncompressed VK bytes produced by `bun contracts/scripts/vk-json-to-bytes.ts`.
// Each G1 point is 96 bytes (x || y), each G2 point is 192 bytes
// (x_c0 || x_c1 || y_c0 || y_c1).
const VK_ALPHA: &[u8; 96] = include_bytes!("vk/vk_alpha.bin");
const VK_BETA: &[u8; 192] = include_bytes!("vk/vk_beta.bin");
const VK_GAMMA: &[u8; 192] = include_bytes!("vk/vk_gamma.bin");
const VK_DELTA: &[u8; 192] = include_bytes!("vk/vk_delta.bin");

// 12 IC points for our 11 public signals (nPublic + 1).
const VK_IC_0: &[u8; 96] = include_bytes!("vk/vk_ic_0.bin");
const VK_IC_1: &[u8; 96] = include_bytes!("vk/vk_ic_1.bin");
const VK_IC_2: &[u8; 96] = include_bytes!("vk/vk_ic_2.bin");
const VK_IC_3: &[u8; 96] = include_bytes!("vk/vk_ic_3.bin");
const VK_IC_4: &[u8; 96] = include_bytes!("vk/vk_ic_4.bin");
const VK_IC_5: &[u8; 96] = include_bytes!("vk/vk_ic_5.bin");
const VK_IC_6: &[u8; 96] = include_bytes!("vk/vk_ic_6.bin");
const VK_IC_7: &[u8; 96] = include_bytes!("vk/vk_ic_7.bin");
const VK_IC_8: &[u8; 96] = include_bytes!("vk/vk_ic_8.bin");
const VK_IC_9: &[u8; 96] = include_bytes!("vk/vk_ic_9.bin");
const VK_IC_10: &[u8; 96] = include_bytes!("vk/vk_ic_10.bin");
const VK_IC_11: &[u8; 96] = include_bytes!("vk/vk_ic_11.bin");

/// Groth16 verify over BLS12-381. Returns `true` iff the pairing equation
///
///     e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
///
/// holds, where `vk_x = IC[0] + sum_i(pub_signals[i] * IC[i+1])`.
///
/// `pub_signals` MUST have exactly 11 elements (10 public inputs + 1
/// public output from the circuit); mismatched length fails the check.
pub fn verify_groth16(
    env: &Env,
    proof_a: G1Affine,
    proof_b: G2Affine,
    proof_c: G1Affine,
    pub_signals: Vec<Fr>,
) -> bool {
    let ic_len = 12u32;
    if pub_signals.len() + 1 != ic_len {
        return false;
    }

    let alpha = G1Affine::from_array(env, VK_ALPHA);
    let beta = G2Affine::from_array(env, VK_BETA);
    let gamma = G2Affine::from_array(env, VK_GAMMA);
    let delta = G2Affine::from_array(env, VK_DELTA);
    let ic = ic_points(env);

    let bls = env.crypto().bls12_381();

    // vk_x = ic[0] + sum(pub_signals[i] * ic[i+1])
    let mut vk_x = ic.get(0).unwrap();
    for (index, signal) in pub_signals.iter().enumerate() {
        let ic_point = ic.get((index as u32) + 1).unwrap();
        let prod = bls.g1_mul(&ic_point, &signal);
        vk_x = bls.g1_add(&vk_x, &prod);
    }

    let neg_a = -proof_a;
    let vp1 = vec![env, neg_a, alpha, vk_x, proof_c];
    let vp2 = vec![env, proof_b, beta, gamma, delta];

    bls.pairing_check(vp1, vp2)
}

fn ic_points(env: &Env) -> Vec<G1Affine> {
    vec![
        env,
        G1Affine::from_array(env, VK_IC_0),
        G1Affine::from_array(env, VK_IC_1),
        G1Affine::from_array(env, VK_IC_2),
        G1Affine::from_array(env, VK_IC_3),
        G1Affine::from_array(env, VK_IC_4),
        G1Affine::from_array(env, VK_IC_5),
        G1Affine::from_array(env, VK_IC_6),
        G1Affine::from_array(env, VK_IC_7),
        G1Affine::from_array(env, VK_IC_8),
        G1Affine::from_array(env, VK_IC_9),
        G1Affine::from_array(env, VK_IC_10),
        G1Affine::from_array(env, VK_IC_11),
    ]
}
